name: React CI/CD

# 트리거 : PUSH, PR(Pull Request) 이벤트 발생 시 작동, 브랜치는 main
# 만약 프론트엔드, 백엔드 통합 시 특정디렉토리가 업데이트될 때 반영해라 등 세부 조건 추가 가능
on:
  push:
    branch:
      - main
  pull_request:
    branch:
      - main
        
# 해야할 일
jobs:
  react-deploy:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃 -> github의 저장소로부터 소스 체크아웃
      - name: Checkout repository resource
        uses: actions/checkout@v2

      # 환경변수 동적 생성 -> .env 파일 생성(ec2 정보 세팅), 기존코드 수정(보안)
      - name: .env 환경 변수 동적 생성
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > .env
          pwd
          ls -al

      # 빌드를 위한 조건 -> nodejs 설치
      # npm install 라이브러리 설치
      # 빌드
      # 빌드의 결과물을 EC2 업로드
      # 뒷정리 (업로드 결과 -> nginx의 root로 이동(설정), 디렉토리 정리)