name: React CI/CD

# 트리거 : PUSH, PR(Pull Request) 이벤트 발생 시 작동, 브랜치는 main
# 만약 프론트엔드, 백엔드 통합 시 특정디렉토리가 업데이트될 때 반영해라 등 세부 조건 추가 가능
on:
  push:
    branch:
      - main
  pull_request:
    branch:
      - main
        
# 해야할 일
jobs:
  react-deploy:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃 -> github의 저장소로부터 소스 체크아웃
      - name: Checkout repository resource
        uses: actions/checkout@v2

      # 환경변수 동적 생성 -> .env 파일 생성(ec2 정보 세팅), 기존코드 수정(보안)
      - name: .env 환경 변수 동적 생성
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > .env
          pwd
          ls -al

      # 빌드를 위한 조건 -> nodejs 설치
      - name: NodeJS 설치
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # npm install 라이브러리 설치
      - name: install 독립 라이브러리
        run: npm install

      # 단위 테스트 -> 생략
      # - name: 단위테스트
      #   run: npm test

      # 빌드
      - name: 빌드
        run: |
          npm run build
          ls ./build

      # 빌드의 결과물을 EC2 업로드
      # 대상 위치에 존재하는 모든 리소스 -> EC2의 ~/client 하위에 복사해라
      - name: EC2에 빌드된 파일/폴더 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./build/*
          target: /home/ubuntu/client


      # 뒷정리 (업로드 결과 -> nginx의 root로 이동(설정), 디렉토리 정리)
      - name: SSH로 EC2에 정리 후, 접속 및 서버가동
        uses: appleboy/ssh-action@v1.2.0
        # script_stop : true -> 오류나면 중단
        # 처리할 반복적 작업
        # 1. 기존 jar 파일 삭제 처리 (업로드 위치, 구동 위치 구분)
        #    구동 위치 : /home/ubuntu/server/web <- 설정(가정)
        #    rm -rf 대상 => 대상의 폴더 및 하위 파일까지 모두다 삭제
        # 2. 새롭게 폴더 생성 /home/ubuntu/server/web
        #    mkdir /home/ubuntu/server/web
        # 3. jar 파일 이동 (~/demo/*.jar => ~/web/*.jar)
        #    mv /home/ubuntu/server/demo/run.jar /home/ubuntu/server/web/run.jar
        # 4. jar 파일이 존재하는 위치로 이동
        #    cd /home/ubuntu/server/web
        # 5. 서버 중단 -> 8080포트를 사용하는 프로세스 중단
        #    sudo fuser -k -n tcp 8080 || true
        #    무조건 다음 단계로 넘어가게 처리 (|| true)
        # 6. 서버 구동
        #    액세스, 에러 로그 등 전체 로그를 output.log으로 출력
        #    nohup java -jar run.jar > ./output.log 2>&1 &
        # 7. 뒷정리
        #    rm -rf /home/ubuntu/server/demo
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /var/www/html
            mkdir /var/www/html
            mv /home/ubuntu/client/build/* /var/www/html
            cd /var/www/html
            sudo fuser -k -n tcp 8080 || true
            sudo systemctl restart nginx
            rm -rf /home/ubuntu/client/build/